### ISSUE TITLE
[Tree] nodes should implement pseudoclasses for CSS styling

### ISSUE THREAD

**Issue by joshburnett** [Textualize/textual#1474]
Tree nodes can currently be styled via CSS, but pseudoclasses like :hover and :selected are not implemented as they are in other classes. As such, applying styling as the user selects and deselects nodes is a manual affair. The current workaround involves manipulating the label directly, adding and removing Rich styling markup.

To be added by @willmcgugan

**Comment by davep** [comment]
See also #1471 which would likely overlap with this.

**Comment by davep** [comment]
Looking into this today, and I think there could be some confusion around this, most likely down to documentation for some of the styling options not being done until now.

As I'm sure you'll know, the content of a `Tree` isn't widgets, so not part of the DOM, and not really capable of being styled via the normal CSS route. This also means that, for example, a node in the tree isn't ever focused or anything similar (the `Tree` will have focus, but the `Node` within it won't). However, there are "component classes" related to parts of the display of a `Tree` which can be modified from CSS. These include:

| Class | Description |
| :- | :- |
| `tree--cursor` | Targets the cursor. |
| `tree--guides` | Targets the indentation guides. |
| `tree--guides-hover` | Targets the indentation guides under the cursor. |
| `tree--guides-selected` | Targets the indentation guides that are selected. |
| `tree--highlight` | Targets the highlighted items. |
| `tree--highlight-line` | Targets the lines under the cursor. |
| `tree--label` | Targets the (text) labels of the items. |

If you take a look at the source for the `Tree` widget [you'll see how they can be used to style things](https://github.com/Textualize/textual/blob/d3fdcbe250cf399932822a3708e168037499b84c/src/textual/widgets/_tree.py#L321-L361).

By way of illustration, I offer the world's ugliest `Tree`:

```python
from textual.app          import App, ComposeResult
from textual.containers   import Vertical
from textual.widgets      import Header, Footer, Tree, TextLog, TreeNode
from textual.binding      import Binding

class Sandbox( Tree[ None ] ):
    pass

class TreeSandbox( App[ None ] ):

    CSS = """
    Tree {
        width: 1fr;
        height: 2fr;
        border: round darkred;
        background: green;
        color: red;
    }

    Tree > .tree--cursor {
        background: black;
        color: red;
    }

    Tree > .tree--guides {
        color: grey;
    }

    Tree > .tree--guides-hover {
        color: purple;
    }

    Tree > .tree--guides-selected {
        color: cyan;
        background: orange;
    }

    TextLog {
        height: 1fr;
        border: round darkred;
    }

    *:focus {
        border: double green;
    }
    """

    BINDINGS = [
        *[ Binding( str( n ), f"select( {n} )", f"Select {n}" ) for n in range( 10 ) ],
        *[ Binding( f"f{n}", f"expand( {n} )", f"Expand {n}" ) for n in range( 10 ) ],
    ]


    def __init__( self ):
        super().__init__()
        self.nodes: list[ TreeNode[ None ] ] = []

    def compose( self ) -> ComposeResult:
        yield Header()
        self.sandbox = Sandbox( "Tree Sandbox" )
        yield Vertical( self.sandbox, TextLog() )
        yield Footer()

    def on_mount( self ) -> None:
        for node in range( 10 ):
            self.nodes.append(
                self.sandbox.root.add( f"This is parent node {node}" )
            )
            for child in range( 10 ):
                self.nodes[ -1 ].add_leaf(
                    f"Child node {child}"
                )
        deeply = 0
        node   = self.nodes[ 0 ]
        while deeply < 50:
            node = node.add( "We must go deeper" )
            deeply += 1
        self.sandbox.focus()

    def on_tree_node_collapsed( self, event: Tree.NodeCollapsed ) -> None:
        self.query_one( TextLog ).write( ( event, event.node ) )

    def on_tree_node_expanded( self, event: Tree.NodeExpanded ) -> None:
        self.query_one( TextLog ).write( ( event, event.node ) )

    def on_tree_node_highlighted( self, event: Tree.NodeHighlighted ) -> None:
        self.query_one( TextLog ).write( ( event, event.node ) )

    def on_tree_node_selected( self, event: Tree.NodeSelected ) -> None:
        self.query_one( TextLog ).write( ( event, event.node ) )

if __name__ == "__main__":
    TreeSandbox().run()
```

Does this help and let you do what you're aiming for?

**Comment by joshburnett** [comment]
Excellent! I'll take a look at this.

**Comment by joshburnett** [comment]
I think I'm understanding the component classes now. However, while the event system makes a distinction between 'highlighting' a node and 'selecting' one (with the NodeHighlighted and NodeSelected events), there doesn't seem to be a component class for the 'selected' node, just the 'highlighted' one (via the .tree--cursor).

I'd like to be able to move the cursor up and down a tree, but not changing the 'selected' node until I press the Enter key. The event system seems to support this, as just moving the cursor triggers the NodeHighlighted event, while the NodeSelected event is only triggered by the Enter key (or selecting via mouse). However, the styling doesn't seem to match up with this use case.

**Comment by davep** [comment]
> I think I'm understanding the component classes now. However, while the event system makes a distinction between 'highlighting' a node and 'selecting' one (with the NodeHighlighted and NodeSelected events), there doesn't seem to be a component class for the 'selected' node, just the 'highlighted' one (via the .tree--cursor).

That's correct. It should be kept in mind that there's a difference between the styling, how things look, and the events that get sent. A `NodeHighlighted` event is emitted when the `Tree`'s cursor changes to a different node. In this regard, from a styling point of view, nodes only have the two states: highlighted (the `Tree`'s cursor is on them), and not highlighted. `NodeSelected` on the other hand doesn't have a connection to an appearance of a node; `NodeSelected` is an event that is sent when the user specifically selects the node (selecting is either the user hitting <kbd>Enter</kbd> on a highlighted node, or using the mouse to click on a node).

In other words: `Selected` isn't a style for the `Tree`, it's an action the user takes.

> I'd like to be able to move the cursor up and down a tree, but not changing the 'selected' node until I press the Enter key.

As you go on to point out: that is how `Tree` works. If I run the code I posted above, with 0.10.1 of Textual, as I use the cursor keys to move around the `Tree`, I only get `NodeHighlighted` events. Only when I press <kbd>Enter</kbd> on a node do I get a `NodeSelected` event. All of that is, of course, different from how you style nodes. It's not really clear to me what you would expect to see. When you press a cursor key it moves the highlight (tree node cursor) and sends out a `NodeHighlighted` event. When the user presses <key>Enter</key> an event (`NodeSelected`) is sent to say *"hey, the user just hit enter on this highlighted node, you might want to do something for them"* -- that's not a style thing, that's a call to action thing.

**Comment by joshburnett** [comment]
> NodeSelected on the other hand doesn't have a connection to an appearance of a node; NodeSelected is an event that is sent when the user specifically selects the node (selecting is either the user hitting Enter on a highlighted node, or using the mouse to click on a node).

Exactly, and this is the feature that I believe is missing. There is currently no built-in way to visually indicate which node is selected. As I said in my initial note above:

> As such, applying styling as the user selects and deselects nodes is a manual affair. The current workaround involves manipulating the label directly, adding and removing Rich styling markup.

Without this visual indicator, the state of the application is not always clear. If I have another part of the app that updates when a tree node is selected, then as the cursor is moved around the tree without selecting, the application state is not visually consistent. The state of the dependent content does not match the visual state of the tree.

If I had a way to visually style the selected node separate from merely having the cursor on it, I could do something like made the text italic, bold, or a different color. This is doable now, but only through direct manipulation of the label, applying and removing styling markup as the selection changes.

**Comment by joshburnett** [comment]
Re-reading your note and looking through the Tree API again, I understand your point about 'selected' not currently being a state that a node is in, only an action that can be taken. (For any others reading this: there is no Tree method that returns the currently 'selected' node of the Tree, and there is no TreeNode API to return whether a node is currently 'selected' or not. It's just not a state that gets tracked.)

I think this is a missing feature, and is fundamentally the root of my issue with the Tree model here.

**Comment by joshburnett** [comment]
(Totally unintentional pun there, I swear!)

**Comment by davep** [comment]
Okay, I can see better what you're after now. Yup, that's the heart of it here: there's no such thing as a "selected state", just a *"the user indicated they want to do something with this"* action. From what I can see I think you're going about it the right way; it's likely how I'd approach it too: when a selected event is received, if I want to make that node visually "sticky" in some way, I'd update the label to reflect it.

If this is something you're going to want to do often in your apps it might even make sense to have your own subclassed tree that handles this for you. It should be even easier to do once 0.11.0 is released as there's a change coming to how events get sent out such that they start on `self`, rather than starting on the `parent` (#1738).

**Comment by joshburnett** [comment]
One more note to make the case for having _selected_ be a state (with styling) and not just an action. If you're using the tree view to change visible state of another part of the app, as soon as the user navigates away and the tree loses focus, the tree cursor goes away and it's no longer clear what node the cursor was even on (let alone if that cursor was on a different node than the one that had been last selected).

I can implement this myself (and will for now), but I think it would be a common enough need to (eventually) implement as part of the core Tree functionality, rather than requiring anyone who cares about _selected_ state have to implement it themselves.

**Comment by davep** [comment]
The removal of any highlighted state on loss of focus has been addressed by https://github.com/Textualize/textual/pull/1703 which is in today's release.

**Comment by joshburnett** [comment]
That's great to see, and it's needed. However, it still doesn't handle the cases where _selected_ is a state the user cares about.

(Great to see the new release today! Gonna go and see what other goodies are in it now...)

**Comment by davep** [comment]
> However, it still doesn't handle the cases where selected is a state the user cares about.

Sure thing; I was just highlighting it as you reported the same thing as #1471 so I wanted you to know that it had been addressed a couple or so weeks back and was in today's release.

As for the issue of extending the current `Tree` widget ti introduce a selected *state* of some sort, we feel that's not really right for the base `Tree` in the library; it's something people should be able to build on top of the `Tree` though.

> (Great to see the new release today! Gonna go and see what other goodies are in it now...)

Thanks! Hope you find some useful things in it! :-)
