### ISSUE TITLE
Some markdown component classes don't refresh on CSS update

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3464]
The component classes `s`, `strong`, `em`, and `code_inline` aren't refreshed when CSS is reloaded and those are changed.
However, the component classes `markdown-table--header` and `markdown-table--lines` do refresh.

The video below shows this. Code is included after the video.

https://github.com/Textualize/textual/assets/5621605/d0f3d624-c510-4955-bfc8-5d53df590e1d

<details>
<summary>App code</summary>

```py
from textual.app import App
from textual.widgets import Markdown

MD = """
# This is a header

| col1 | col2 |
| :- | :- |
| value 1 | value 2 |

Here's some code: `from itertools import product`.
**Bold text**
_Emphasized text_
~~strikethrough~~
"""


class MyApp(App):
    CSS_PATH = "markdown.tcss"

    def compose(self):
        yield Markdown(MD)


if __name__ == "__main__":
    MyApp().run()
```

```sass
.code_inline,
.em,
.strong,
.s,
.markdown-table--header,
.markdown-table--lines,
{
    color: blue;
}
```

</details>

**Comment by willmcgugan** [comment]
I think this is fixed. Please confirm and close the issue if that's the case.

**Comment by rodrigogiraoserrao** [comment]
This is still not fixed. Using the code from the first comment I'm able to reproduce the behaviour demonstrated in the screen recording.

**Comment by willmcgugan** [comment]
Do you want to take a look at this? Suspect it is an easy fix.
