### ISSUE TITLE
`scrollbar-gutter` causes `loading` overlay to not fully overlay

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3733]
This has turned up with Textual 0.42. If you have a widget that is styled `scrollbar-gutter: stable`, the `loading` overlay seems to "leak" whatever's underneath on the edge of the indicator. Using this code (using an `OptionList` as that's the widget I discovered it with):

```python
from textual.app import App, ComposeResult
from textual.widgets import OptionList

class LoadingOverlayRedux(App[None]):

    CSS = """
    OptionList {
        scrollbar-gutter: stable;
        width: 1fr;
        height: 1fr;
    }
    """

    BINDINGS = [
        ("space", "toggle")
    ]

    def compose(self) -> ComposeResult:
        yield OptionList(*[
            ("X" * 500) for _ in range(1_000)
        ])

    def action_toggle(self) -> None:
        self.query_one(OptionList).loading = not self.query_one(OptionList).loading

if __name__ == "__main__":
    LoadingOverlayRedux().run()
```

it initially looks like this:

![Screenshot 2023-11-22 at 19 55 03](https://github.com/Textualize/textual/assets/28237/2c649553-4b13-44ec-9c3c-5d4816a3caba)

and then if I toggle `loading`:

![Screenshot 2023-11-22 at 19 55 13](https://github.com/Textualize/textual/assets/28237/20db90df-fd95-4cba-9a9c-66e90bc5cdf8)

**Comment by willmcgugan** [comment]
Fixed now.

**Comment by davep** [comment]
> Fixed now.

@willmcgugan Which PR fixed this, as I'm still seeing the exact same problem with 0.43.2 and also `main`?

**Comment by willmcgugan** [comment]
Seems to be more than scroll gutter at play. If you scroll down you don't see the loading indicator. Like its not taking in to account scroll position.
