### ISSUE TITLE
A single character wide TextArea flickers

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4067]
It's a silly thing to do, but if you shrink the TextArea to something really small it flickers. Possibly because of scrollbars.

**Comment by TomJGooding** [comment]
I might be misunderstanding what you mean by a "single character wide TextArea" but I can't seem to reproduce this?

**Comment by willmcgugan** [comment]
If you have  a TextArea, and you reduce the widow size so the TextArea is one character wide it flickers. At least it did at the time of this issue. Maybe it has been fixed...

**Comment by rodrigogiraoserrao** [comment]
It took me a couple of tries but this is still an issue:


https://github.com/Textualize/textual/assets/5621605/3d2dabdb-42b4-481d-ba88-1e72ab8c189e
